version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
            
        commands:
            - pip install --upgrade pip
        # Install dependencies needed for running the static analysis
            - pip install -r requirement.txt 
    pre_build:
        commands:
            - python --version
             
artifacts:
    files:
        - '**/*'